<?php
//MAD
function get_bl_cities(){

	 
$bl_cities = array("ADSM_BL_CITY_SOFIA","ADSM_BL_CITY_PLOVDIV","ADSM_BL_CITY_VARNA","ADSM_BL_CITY_BURGAS","ADSM_BL_CITY_RUSE","ADSM_BL_CITY_STARA_ZAGORA","ADSM_BL_CITY_PLEVEN","ADSM_BL_CITY_SLIVEN","ADSM_BL_CITY_DOBRICH","ADSM_BL_CITY_PERNIK","ADSM_BL_CITY_SHUMEN","ADSM_BL_CITY_HASKOVO","ADSM_BL_CITY_YAMBOL","ADSM_BL_CITY_PAZARDZHIK","ADSM_BL_CITY_BLAGOEVGRAD","ADSM_BL_CITY_VELIKO_TARNOVO","ADSM_BL_CITY_VRATSA","ADSM_BL_CITY_GABROVO","ADSM_BL_CITY_ASENOVGRAD","ADSM_BL_CITY_VIDIN","ADSM_BL_CITY_KAZANLAK","ADSM_BL_CITY_KYUSTENDIL","ADSM_BL_CITY_KARDZHALI","ADSM_BL_CITY_MONTANA","ADSM_BL_CITY_DIMITROVGRAD","ADSM_BL_CITY_TARGOVISHTE","ADSM_BL_CITY_LOVECH","ADSM_BL_CITY_SILISTRA","ADSM_BL_CITY_DUPNITSA","ADSM_BL_CITY_SVISHTOV","ADSM_BL_CITY_RAZGRAD","ADSM_BL_CITY_GORNA_ORYAHOVITSA","ADSM_BL_CITY_SMOLYAN","ADSM_BL_CITY_PETRICH","ADSM_BL_CITY_SANDANSKI","ADSM_BL_CITY_SAMOKOV","ADSM_BL_CITY_SEVLIEVO","ADSM_BL_CITY_LOM","ADSM_BL_CITY_KARLOVO","ADSM_BL_CITY_VELINGRAD","ADSM_BL_CITY_NOVA_ZAGORA","ADSM_BL_CITY_TROYAN","ADSM_BL_CITY_AYTOS","ADSM_BL_CITY_BOTEVGRAD","ADSM_BL_CITY_GOTSE_DELCHEV","ADSM_BL_CITY_PESHTERA","ADSM_BL_CITY_HARMANLI","ADSM_BL_CITY_KARNOBAT","ADSM_BL_CITY_SVILENGRAD","ADSM_BL_CITY_PANAGYURISHTE","ADSM_BL_CITY_CHIRPAN","ADSM_BL_CITY_POPOVO","ADSM_BL_CITY_RAKOVSKI","ADSM_BL_CITY_RADOMIR","ADSM_BL_CITY_NOVI_ISKAR","ADSM_BL_CITY_KOZLODUY","ADSM_BL_CITY_PARVOMAY","ADSM_BL_CITY_BERKOVITSA","ADSM_BL_CITY_CHERVEN_BRYAG","ADSM_BL_CITY_POMORIE","ADSM_BL_CITY_IHTIMAN","ADSM_BL_CITY_RADNEVO","ADSM_BL_CITY_PROVADIYA","ADSM_BL_CITY_NOVI_PAZAR","ADSM_BL_CITY_RAZLOG","ADSM_BL_CITY_BYALA_SLATINA","ADSM_BL_CITY_NESEBAR","ADSM_BL_CITY_BALCHIK","ADSM_BL_CITY_KOSTINBROD","ADSM_BL_CITY_STAMBOLIYSKI","ADSM_BL_CITY_KAVARNA","ADSM_BL_CITY_KNEZHA","ADSM_BL_CITY_PAVLIKENI","ADSM_BL_CITY_MEZDRA","ADSM_BL_CITY_ETROPOLE","ADSM_BL_CITY_LEVSKI","ADSM_BL_CITY_TETEVEN","ADSM_BL_CITY_ELHOVO","ADSM_BL_CITY_BANKYA","ADSM_BL_CITY_TRYAVNA","ADSM_BL_CITY_LUKOVIT","ADSM_BL_CITY_TUTRAKAN","ADSM_BL_CITY_SREDETS","ADSM_BL_CITY_SOPOT","ADSM_BL_CITY_BYALA","ADSM_BL_CITY_VELIKI_PRESLAV","ADSM_BL_CITY_ISPERIH","ADSM_BL_CITY_BELENE","ADSM_BL_CITY_OMURTAG","ADSM_BL_CITY_BANSKO","ADSM_BL_CITY_KRICHIM","ADSM_BL_CITY_GALABOVO","ADSM_BL_CITY_DEVNYA","ADSM_BL_CITY_SEPTEMVRI","ADSM_BL_CITY_RAKITOVO","ADSM_BL_CITY_LYASKOVETS","ADSM_BL_CITY_SVOGE","ADSM_BL_CITY_AKSAKOVO","ADSM_BL_CITY_KUBRAT","ADSM_BL_CITY_DRYANOVO","ADSM_BL_CITY_BELOSLAV","ADSM_BL_CITY_PIRDOP","ADSM_BL_CITY_LYUBIMETS","ADSM_BL_CITY_MOMCHILGRAD","ADSM_BL_CITY_SLIVNITSA","ADSM_BL_CITY_HISARYA","ADSM_BL_CITY_ZLATOGRAD","ADSM_BL_CITY_KOSTENETS","ADSM_BL_CITY_DEVIN","ADSM_BL_CITY_GENERAL_TOSHEVO","ADSM_BL_CITY_SIMEONOVGRAD","ADSM_BL_CITY_SIMITLI","ADSM_BL_CITY_ELIN_PELIN","ADSM_BL_CITY_DOLNI_CHIFLIK","ADSM_BL_CITY_TERVEL","ADSM_BL_CITY_DULOVO","ADSM_BL_CITY_VARSHETS","ADSM_BL_CITY_KOTEL","ADSM_BL_CITY_MADAN","ADSM_BL_CITY_STRALDZHA","ADSM_BL_CITY_SAEDINENIE","ADSM_BL_CITY_BOBOV_DOL","ADSM_BL_CITY_TSAREVO","ADSM_BL_CITY_KUKLEN","ADSM_BL_CITY_TVARDITSA","ADSM_BL_CITY_YAKORUDA","ADSM_BL_CITY_ELENA","ADSM_BL_CITY_TOPOLOVGRAD","ADSM_BL_CITY_BOZHURISHTE","ADSM_BL_CITY_CHEPELARE","ADSM_BL_CITY_ORYAHOVO","ADSM_BL_CITY_SOZOPOL","ADSM_BL_CITY_BELOGRADCHIK","ADSM_BL_CITY_PERUSHTITSA","ADSM_BL_CITY_ZLATITSA","ADSM_BL_CITY_STRAZHITSA");

	$bl_cities_lang_sort = array();
	foreach ($bl_cities as $bl_citiy) {
		
		array_push($bl_cities_lang_sort , JText::_($bl_citiy));
	}
	
	array_multisort($bl_cities_lang_sort, $bl_cities);


	$get_bl_cities = '';
	$i = 0;
	foreach ($bl_cities as $bl_citiy) {
		if ($i != 0) $get_bl_cities .= ',';
	$get_bl_cities .= 'new Array("'.JText::_($bl_citiy).'","'.$bl_citiy.'" )';
		$i++;
	}

	echo $get_bl_cities;
}


function get_dimous_cy() {
	$dimoi_cy = array(
"ADSM_CY_CITY_AMOXOSTOS_1", "ADSM_CY_CITY_AMOXOSTOS_2", "ADSM_CY_CITY_AMOXOSTOS_3", "ADSM_CY_CITY_AMOXOSTOS_4", "ADSM_CY_CITY_AMOXOSTOS_5", "ADSM_CY_CITY_AMOXOSTOS_6", "ADSM_CY_CITY_AMOXOSTOS_7", "ADSM_CY_CITY_AMOXOSTOS_8", "ADSM_CY_CITY_AMOXOSTOS_9", "ADSM_CY_CITY_AMOXOSTOS_10", "ADSM_CY_CITY_AMOXOSTOS_11", "ADSM_CY_CITY_AMOXOSTOS_12", "ADSM_CY_CITY_AMOXOSTOS_13", "ADSM_CY_CITY_AMOXOSTOS_14", "ADSM_CY_CITY_AMOXOSTOS_15", "ADSM_CY_CITY_AMOXOSTOS_16", "ADSM_CY_CITY_AMOXOSTOS_17", "ADSM_CY_CITY_AMOXOSTOS_18", "ADSM_CY_CITY_LARNAKA_1", "ADSM_CY_CITY_LARNAKA_2", "ADSM_CY_CITY_LARNAKA_3", "ADSM_CY_CITY_LARNAKA_4", "ADSM_CY_CITY_LARNAKA_5", "ADSM_CY_CITY_LARNAKA_6", "ADSM_CY_CITY_LARNAKA_7", "ADSM_CY_CITY_LARNAKA_8", "ADSM_CY_CITY_LARNAKA_9", "ADSM_CY_CITY_LARNAKA_10", "ADSM_CY_CITY_LARNAKA_11", "ADSM_CY_CITY_LARNAKA_12", "ADSM_CY_CITY_LARNAKA_13", "ADSM_CY_CITY_LARNAKA_14", "ADSM_CY_CITY_LARNAKA_15", "ADSM_CY_CITY_LARNAKA_16", "ADSM_CY_CITY_LARNAKA_17", "ADSM_CY_CITY_LARNAKA_18", "ADSM_CY_CITY_LARNAKA_19", "ADSM_CY_CITY_LARNAKA_20", "ADSM_CY_CITY_LARNAKA_21", "ADSM_CY_CITY_LARNAKA_22", "ADSM_CY_CITY_LARNAKA_23", "ADSM_CY_CITY_LARNAKA_24", "ADSM_CY_CITY_LARNAKA_25", "ADSM_CY_CITY_LARNAKA_26", "ADSM_CY_CITY_LARNAKA_27", "ADSM_CY_CITY_LARNAKA_28", "ADSM_CY_CITY_LARNAKA_29", "ADSM_CY_CITY_LARNAKA_30", "ADSM_CY_CITY_LARNAKA_31", "ADSM_CY_CITY_LARNAKA_32", "ADSM_CY_CITY_LARNAKA_33", "ADSM_CY_CITY_LARNAKA_34", "ADSM_CY_CITY_LARNAKA_35", "ADSM_CY_CITY_LARNAKA_36", "ADSM_CY_CITY_LARNAKA_37", "ADSM_CY_CITY_LARNAKA_38", "ADSM_CY_CITY_LARNAKA_39", "ADSM_CY_CITY_LARNAKA_40", "ADSM_CY_CITY_LARNAKA_41", "ADSM_CY_CITY_LARNAKA_42", "ADSM_CY_CITY_LARNAKA_43", "ADSM_CY_CITY_LARNAKA_44", "ADSM_CY_CITY_LARNAKA_45", "ADSM_CY_CITY_LARNAKA_46", "ADSM_CY_CITY_LARNAKA_47", "ADSM_CY_CITY_LARNAKA_48", "ADSM_CY_CITY_LARNAKA_49", "ADSM_CY_CITY_LARNAKA_50", "ADSM_CY_CITY_LARNAKA_51", "ADSM_CY_CITY_LARNAKA_52", "ADSM_CY_CITY_LARNAKA_53", "ADSM_CY_CITY_LARNAKA_54", "ADSM_CY_CITY_LARNAKA_55", "ADSM_CY_CITY_LARNAKA_56", "ADSM_CY_CITY_LARNAKA_57", "ADSM_CY_CITY_LARNAKA_58", "ADSM_CY_CITY_LARNAKA_59", "ADSM_CY_CITY_LEMESOS_1", "ADSM_CY_CITY_LEMESOS_2", "ADSM_CY_CITY_LEMESOS_3", "ADSM_CY_CITY_LEMESOS_4", "ADSM_CY_CITY_LEMESOS_5", "ADSM_CY_CITY_LEMESOS_6", "ADSM_CY_CITY_LEMESOS_7", "ADSM_CY_CITY_LEMESOS_8", "ADSM_CY_CITY_LEMESOS_9", "ADSM_CY_CITY_LEMESOS_10", "ADSM_CY_CITY_LEMESOS_11", "ADSM_CY_CITY_LEMESOS_12", "ADSM_CY_CITY_LEMESOS_13", "ADSM_CY_CITY_LEMESOS_14", "ADSM_CY_CITY_LEMESOS_15", "ADSM_CY_CITY_LEMESOS_16", "ADSM_CY_CITY_LEMESOS_17", "ADSM_CY_CITY_LEMESOS_18", "ADSM_CY_CITY_LEMESOS_19", "ADSM_CY_CITY_LEMESOS_20", "ADSM_CY_CITY_LEMESOS_21", "ADSM_CY_CITY_LEMESOS_22", "ADSM_CY_CITY_LEMESOS_23", "ADSM_CY_CITY_LEMESOS_24", "ADSM_CY_CITY_LEMESOS_25", "ADSM_CY_CITY_LEMESOS_26", "ADSM_CY_CITY_LEMESOS_27", "ADSM_CY_CITY_LEMESOS_28", "ADSM_CY_CITY_LEMESOS_29", "ADSM_CY_CITY_LEMESOS_30", "ADSM_CY_CITY_LEMESOS_31", "ADSM_CY_CITY_LEMESOS_32", "ADSM_CY_CITY_LEMESOS_33", "ADSM_CY_CITY_LEMESOS_34", "ADSM_CY_CITY_LEMESOS_35", "ADSM_CY_CITY_LEMESOS_36", "ADSM_CY_CITY_LEMESOS_37", "ADSM_CY_CITY_LEMESOS_38", "ADSM_CY_CITY_LEMESOS_39", "ADSM_CY_CITY_LEMESOS_40", "ADSM_CY_CITY_LEMESOS_41", "ADSM_CY_CITY_LEMESOS_42", "ADSM_CY_CITY_LEMESOS_43", "ADSM_CY_CITY_LEMESOS_44", "ADSM_CY_CITY_LEMESOS_45", "ADSM_CY_CITY_LEMESOS_46", "ADSM_CY_CITY_LEMESOS_47", "ADSM_CY_CITY_LEMESOS_48", "ADSM_CY_CITY_LEMESOS_49", "ADSM_CY_CITY_LEMESOS_50", "ADSM_CY_CITY_LEMESOS_51", "ADSM_CY_CITY_LEMESOS_52", "ADSM_CY_CITY_LEMESOS_53", "ADSM_CY_CITY_LEMESOS_54", "ADSM_CY_CITY_LEMESOS_55", "ADSM_CY_CITY_LEMESOS_56", "ADSM_CY_CITY_LEMESOS_57", "ADSM_CY_CITY_LEMESOS_58", "ADSM_CY_CITY_LEMESOS_59", "ADSM_CY_CITY_LEMESOS_60", "ADSM_CY_CITY_LEMESOS_61", "ADSM_CY_CITY_LEMESOS_62", "ADSM_CY_CITY_LEMESOS_63", "ADSM_CY_CITY_LEMESOS_64", "ADSM_CY_CITY_LEMESOS_65", "ADSM_CY_CITY_LEMESOS_66", "ADSM_CY_CITY_LEMESOS_67", "ADSM_CY_CITY_LEMESOS_68", "ADSM_CY_CITY_LEMESOS_69", "ADSM_CY_CITY_LEMESOS_70", "ADSM_CY_CITY_LEMESOS_71", "ADSM_CY_CITY_LEMESOS_72", "ADSM_CY_CITY_LEMESOS_73", "ADSM_CY_CITY_LEMESOS_74", "ADSM_CY_CITY_LEMESOS_75", "ADSM_CY_CITY_LEMESOS_76", "ADSM_CY_CITY_LEMESOS_77", "ADSM_CY_CITY_LEMESOS_78", "ADSM_CY_CITY_LEMESOS_79", "ADSM_CY_CITY_LEMESOS_80", "ADSM_CY_CITY_LEMESOS_81", "ADSM_CY_CITY_LEMESOS_82", "ADSM_CY_CITY_LEMESOS_83", "ADSM_CY_CITY_LEMESOS_84", "ADSM_CY_CITY_LEMESOS_85", "ADSM_CY_CITY_LEMESOS_86", "ADSM_CY_CITY_LEMESOS_87", "ADSM_CY_CITY_LEMESOS_88", "ADSM_CY_CITY_LEMESOS_89", "ADSM_CY_CITY_LEMESOS_90", "ADSM_CY_CITY_LEMESOS_91", "ADSM_CY_CITY_LEMESOS_92", "ADSM_CY_CITY_LEMESOS_93", "ADSM_CY_CITY_LEMESOS_94", "ADSM_CY_CITY_LEMESOS_95", "ADSM_CY_CITY_LEMESOS_96", "ADSM_CY_CITY_LEMESOS_97", "ADSM_CY_CITY_LEMESOS_98", "ADSM_CY_CITY_LEMESOS_99", "ADSM_CY_CITY_LEMESOS_100", "ADSM_CY_CITY_LEMESOS_101", "ADSM_CY_CITY_LEMESOS_102", "ADSM_CY_CITY_LEMESOS_103", "ADSM_CY_CITY_LEMESOS_104", "ADSM_CY_CITY_LEMESOS_105", "ADSM_CY_CITY_LEMESOS_106", "ADSM_CY_CITY_LEMESOS_107", "ADSM_CY_CITY_LEMESOS_108", "ADSM_CY_CITY_LEMESOS_109", "ADSM_CY_CITY_LEMESOS_110", "ADSM_CY_CITY_LEMESOS_111", "ADSM_CY_CITY_LEMESOS_112", "ADSM_CY_CITY_LEMESOS_113", "ADSM_CY_CITY_LEMESOS_114", "ADSM_CY_CITY_LEMESOS_115", "ADSM_CY_CITY_LEMESOS_116", "ADSM_CY_CITY_LEMESOS_117", "ADSM_CY_CITY_LEMESOS_118", "ADSM_CY_CITY_LEMESOS_119", "ADSM_CY_CITY_LEMESOS_120", "ADSM_CY_CITY_LEMESOS_121", "ADSM_CY_CITY_LEMESOS_122", "ADSM_CY_CITY_LEMESOS_123", "ADSM_CY_CITY_LEMESOS_124", "ADSM_CY_CITY_LEMESOS_125", "ADSM_CY_CITY_LEMESOS_126", "ADSM_CY_CITY_LEMESOS_127", "ADSM_CY_CITY_LEYKOSIA_1", "ADSM_CY_CITY_LEYKOSIA_2", "ADSM_CY_CITY_LEYKOSIA_3", "ADSM_CY_CITY_LEYKOSIA_4", "ADSM_CY_CITY_LEYKOSIA_5", "ADSM_CY_CITY_LEYKOSIA_6", "ADSM_CY_CITY_LEYKOSIA_7", "ADSM_CY_CITY_LEYKOSIA_8", "ADSM_CY_CITY_LEYKOSIA_9", "ADSM_CY_CITY_LEYKOSIA_10", "ADSM_CY_CITY_LEYKOSIA_11", "ADSM_CY_CITY_LEYKOSIA_12", "ADSM_CY_CITY_LEYKOSIA_13", "ADSM_CY_CITY_LEYKOSIA_14", "ADSM_CY_CITY_LEYKOSIA_15", "ADSM_CY_CITY_LEYKOSIA_16", "ADSM_CY_CITY_LEYKOSIA_17", "ADSM_CY_CITY_LEYKOSIA_18", "ADSM_CY_CITY_LEYKOSIA_19", "ADSM_CY_CITY_LEYKOSIA_20", "ADSM_CY_CITY_LEYKOSIA_21", "ADSM_CY_CITY_LEYKOSIA_22", "ADSM_CY_CITY_LEYKOSIA_23", "ADSM_CY_CITY_LEYKOSIA_24", "ADSM_CY_CITY_LEYKOSIA_25", "ADSM_CY_CITY_LEYKOSIA_26", "ADSM_CY_CITY_LEYKOSIA_27", "ADSM_CY_CITY_LEYKOSIA_28", "ADSM_CY_CITY_LEYKOSIA_29", "ADSM_CY_CITY_LEYKOSIA_30", "ADSM_CY_CITY_LEYKOSIA_31", "ADSM_CY_CITY_LEYKOSIA_32", "ADSM_CY_CITY_LEYKOSIA_33", "ADSM_CY_CITY_LEYKOSIA_34", "ADSM_CY_CITY_LEYKOSIA_35", "ADSM_CY_CITY_LEYKOSIA_36", "ADSM_CY_CITY_LEYKOSIA_37", "ADSM_CY_CITY_LEYKOSIA_38", "ADSM_CY_CITY_LEYKOSIA_39", "ADSM_CY_CITY_LEYKOSIA_40", "ADSM_CY_CITY_LEYKOSIA_41", "ADSM_CY_CITY_LEYKOSIA_42", "ADSM_CY_CITY_LEYKOSIA_43", "ADSM_CY_CITY_LEYKOSIA_44", "ADSM_CY_CITY_LEYKOSIA_45", "ADSM_CY_CITY_LEYKOSIA_46", "ADSM_CY_CITY_LEYKOSIA_47", "ADSM_CY_CITY_LEYKOSIA_48", "ADSM_CY_CITY_LEYKOSIA_49", "ADSM_CY_CITY_LEYKOSIA_50", "ADSM_CY_CITY_LEYKOSIA_51", "ADSM_CY_CITY_LEYKOSIA_52", "ADSM_CY_CITY_LEYKOSIA_53", "ADSM_CY_CITY_LEYKOSIA_54", "ADSM_CY_CITY_LEYKOSIA_55", "ADSM_CY_CITY_LEYKOSIA_56", "ADSM_CY_CITY_LEYKOSIA_57", "ADSM_CY_CITY_LEYKOSIA_58", "ADSM_CY_CITY_LEYKOSIA_59", "ADSM_CY_CITY_LEYKOSIA_60", "ADSM_CY_CITY_LEYKOSIA_61", "ADSM_CY_CITY_LEYKOSIA_62", "ADSM_CY_CITY_LEYKOSIA_63", "ADSM_CY_CITY_LEYKOSIA_64", "ADSM_CY_CITY_LEYKOSIA_65", "ADSM_CY_CITY_LEYKOSIA_66", "ADSM_CY_CITY_LEYKOSIA_67", "ADSM_CY_CITY_LEYKOSIA_68", "ADSM_CY_CITY_LEYKOSIA_69", "ADSM_CY_CITY_LEYKOSIA_70", "ADSM_CY_CITY_LEYKOSIA_71", "ADSM_CY_CITY_LEYKOSIA_72", "ADSM_CY_CITY_LEYKOSIA_73", "ADSM_CY_CITY_LEYKOSIA_74", "ADSM_CY_CITY_LEYKOSIA_75", "ADSM_CY_CITY_LEYKOSIA_76", "ADSM_CY_CITY_LEYKOSIA_77", "ADSM_CY_CITY_LEYKOSIA_78", "ADSM_CY_CITY_LEYKOSIA_79", "ADSM_CY_CITY_LEYKOSIA_80", "ADSM_CY_CITY_LEYKOSIA_81", "ADSM_CY_CITY_LEYKOSIA_82", "ADSM_CY_CITY_LEYKOSIA_83", "ADSM_CY_CITY_LEYKOSIA_84", "ADSM_CY_CITY_LEYKOSIA_85", "ADSM_CY_CITY_LEYKOSIA_86", "ADSM_CY_CITY_LEYKOSIA_87", "ADSM_CY_CITY_LEYKOSIA_88", "ADSM_CY_CITY_LEYKOSIA_89", "ADSM_CY_CITY_LEYKOSIA_90", "ADSM_CY_CITY_LEYKOSIA_91", "ADSM_CY_CITY_LEYKOSIA_92", "ADSM_CY_CITY_LEYKOSIA_93", "ADSM_CY_CITY_LEYKOSIA_94", "ADSM_CY_CITY_LEYKOSIA_95", "ADSM_CY_CITY_LEYKOSIA_96", "ADSM_CY_CITY_LEYKOSIA_97", "ADSM_CY_CITY_LEYKOSIA_98", "ADSM_CY_CITY_LEYKOSIA_99", "ADSM_CY_CITY_LEYKOSIA_100", "ADSM_CY_CITY_LEYKOSIA_101", "ADSM_CY_CITY_LEYKOSIA_102", "ADSM_CY_CITY_LEYKOSIA_103", "ADSM_CY_CITY_LEYKOSIA_104", "ADSM_CY_CITY_LEYKOSIA_105", "ADSM_CY_CITY_LEYKOSIA_106", "ADSM_CY_CITY_LEYKOSIA_107", "ADSM_CY_CITY_LEYKOSIA_108", "ADSM_CY_CITY_LEYKOSIA_109", "ADSM_CY_CITY_LEYKOSIA_110", "ADSM_CY_CITY_LEYKOSIA_111", "ADSM_CY_CITY_LEYKOSIA_112", "ADSM_CY_CITY_LEYKOSIA_113", "ADSM_CY_CITY_LEYKOSIA_114", "ADSM_CY_CITY_LEYKOSIA_115", "ADSM_CY_CITY_LEYKOSIA_116", "ADSM_CY_CITY_LEYKOSIA_117", "ADSM_CY_CITY_LEYKOSIA_118", "ADSM_CY_CITY_LEYKOSIA_119", "ADSM_CY_CITY_LEYKOSIA_120", "ADSM_CY_CITY_LEYKOSIA_121", "ADSM_CY_CITY_LEYKOSIA_122", "ADSM_CY_CITY_LEYKOSIA_123", "ADSM_CY_CITY_LEYKOSIA_124", "ADSM_CY_CITY_LEYKOSIA_125", "ADSM_CY_CITY_LEYKOSIA_126", "ADSM_CY_CITY_LEYKOSIA_127", "ADSM_CY_CITY_LEYKOSIA_128", "ADSM_CY_CITY_PAFOS_1", "ADSM_CY_CITY_PAFOS_2", "ADSM_CY_CITY_PAFOS_3", "ADSM_CY_CITY_PAFOS_4", "ADSM_CY_CITY_PAFOS_5", "ADSM_CY_CITY_PAFOS_6", "ADSM_CY_CITY_PAFOS_7", "ADSM_CY_CITY_PAFOS_8", "ADSM_CY_CITY_PAFOS_9", "ADSM_CY_CITY_PAFOS_10", "ADSM_CY_CITY_PAFOS_11", "ADSM_CY_CITY_PAFOS_12", "ADSM_CY_CITY_PAFOS_13", "ADSM_CY_CITY_PAFOS_14", "ADSM_CY_CITY_PAFOS_15", "ADSM_CY_CITY_PAFOS_16", "ADSM_CY_CITY_PAFOS_17", "ADSM_CY_CITY_PAFOS_18", "ADSM_CY_CITY_PAFOS_19", "ADSM_CY_CITY_PAFOS_20", "ADSM_CY_CITY_PAFOS_21", "ADSM_CY_CITY_PAFOS_22", "ADSM_CY_CITY_PAFOS_23", "ADSM_CY_CITY_PAFOS_24", "ADSM_CY_CITY_PAFOS_25", "ADSM_CY_CITY_PAFOS_26", "ADSM_CY_CITY_PAFOS_27", "ADSM_CY_CITY_PAFOS_28", "ADSM_CY_CITY_PAFOS_29", "ADSM_CY_CITY_PAFOS_30", "ADSM_CY_CITY_PAFOS_31", "ADSM_CY_CITY_PAFOS_32", "ADSM_CY_CITY_PAFOS_33", "ADSM_CY_CITY_PAFOS_34", "ADSM_CY_CITY_PAFOS_35", "ADSM_CY_CITY_PAFOS_36", "ADSM_CY_CITY_PAFOS_37");
	$i = 0;
	
	$cy_cities_lang_sort = array();
	foreach ($dimoi_cy as $dimos) {
		
		array_push($cy_cities_lang_sort , JText::_($dimos));
	}
	
	array_multisort($cy_cities_lang_sort, $dimoi_cy);

	
	foreach ($dimoi_cy as $dimos) {
		if ($i != 0) echo ',';
		echo  'new Array("'.JText::_($dimos).'","'.$dimos.'" )';
		$i++;
	}
}



function get_Nomous_cy() {

	
	$nomoi_cy = array(
	'ADSM_CY_CITY_AMOXOSTOS',
	'ADSM_CY_CITY_LARNAKA',
	'ADSM_CY_CITY_LEMESOS',
	'ADSM_CY_CITY_LEYKOSIA',
	'ADSM_CY_CITY_PAFOS'
	);
	
	
	$i = 0;
	foreach ($nomoi_cy as $nomos) {
		if ($i != 0) echo ',';
		echo get_Nomos_Dimous_cy($nomos);
		$i++;
	}
}
function get_Nomos_Dimous_cy($nomos) {
	$dimoi = '';
	for($i=1; $i < 150; $i++) {
		if (JText::_($nomos.'_'.$i) == $nomos.'_'.$i) break;
		if ($i != 1) $dimoi .= ',';
		$dimoi .= '"'.JText::_($nomos.'_'.$i).'"';
		$dimoi2 =  $nomos.'_'.$i;
		
	}
	$dimoi = 'new Array("'.JText::_($nomos).'", new Array('.$dimoi.'),"'.$nomos.'" )';
	return $dimoi;
}







function get_dimous() {
	$dimoi = array(
"ADSM_CITY_KSANTHI_2", "ADSM_CITY_ATTIKI_ATHINA_1", "ADSM_CITY_ATTIKI_ATHINA_2", "ADSM_CITY_RETHIMNO_1", "ADSM_CITY_ATTIKI_ATHINA_3", "ADSM_CITY_LESVOS_1", "ADSM_CITY_LASITHI_1", "ADSM_CITY_ATTIKI_ATHINA_4", "ADSM_CITY_DODEKANISA_1", "ADSM_CITY_LARISA_1", "ADSM_CITY_EVRITANIA_1", "ADSM_CITY_AITOLOKARNANIA_2", "ADSM_CITY_ATTIKI_ATHINA_5", "ADSM_CITY_ATTIKI_ATHINA_6", "ADSM_CITY_AXAIA_1","ADSM_CITY_ATTIKI_PIREAS_2", "ADSM_CITY_AITOLOKARNANIA_3", "ADSM_CITY_ATTIKI_ATHINA_7", "ADSM_CITY_IMATHIA_1", "ADSM_CITY_EVROS_1", "ADSM_CITY_BOIOTIA_1", "ADSM_CITY_MAGNISIA_1", "ADSM_CITY_PELLA_1", "ADSM_CITY_MAGNISIA_2", "ADSM_CITY_RETHIMNO_2", "ADSM_CITY_ATTIKI_ATHINA_8", "ADSM_CITY_KIKLADES_1", "ADSM_CITY_THESSALONIKI_1", "ADSM_CITY_FLORINA_1", "ADSM_CITY_FTHIOTIDA_1", "ADSM_CITY_SERRES_1", "ADSM_CITY_AITOLOKARNANIA_4", "ADSM_CITY_KIKLADES_2", "ADSM_CITY_ILIA_2", "ADSM_CITY_ILIA_1", "ADSM_CITY_KIKLADES_3", "ADSM_CITY_KIKLADES_4", "ADSM_CITY_RETHIMNO_3", "ADSM_CITY_XANIA_1", "ADSM_CITY_KARDITSA_1", "ADSM_CITY_ARGOLIDA_1", "ADSM_CITY_XALKIDIKI_1", "ADSM_CITY_RODOPI_1", "ADSM_CITY_ARTA_1", "ADSM_CITY_ILIA_3", "ADSM_CITY_ATTIKI_DYTIKI_1", "ADSM_CITY_DODEKANISA_2", "ADSM_CITY_ATTIKI_ANATOLIKI_1", "ADSM_CITY_IRAKLIO_1", "ADSM_CITY_ATTIKI_ANATOLIKI_2", "ADSM_CITY_KORINTHIA_1", "ADSM_CITY_IMATHIA_2", "ADSM_CITY_KOZANI_1", "ADSM_CITY_IRAKLIO_2", "ADSM_CITY_SERRES_2", "ADSM_CITY_IOANNINA_1", "ADSM_CITY_KOZANI_2", "ADSM_CITY_ATTIKI_ATHINA_9", "ADSM_CITY_THESSALONIKI_2", "ADSM_CITY_MAGNISIA_3", "ADSM_CITY_ARKADIA_1", "ADSM_CITY_ATTIKI_ATHINA_10", "ADSM_CITY_ATTIKI_ATHINA_11", "ADSM_CITY_XANIA_2", "ADSM_CITY_ARTA_2", "ADSM_CITY_ATTIKI_ATHINA_12", "ADSM_CITY_ARKADIA_2", "ADSM_CITY_GREVENA_1", "ADSM_CITY_IRAKLIO_3", "ADSM_CITY_ATTIKI_ATHINA_13", "ADSM_CITY_THESSALONIKI_3", "ADSM_CITY_PIERIA_1", "ADSM_CITY_FOKIDA_1", "ADSM_CITY_GREVENA_2", "ADSM_CITY_EVROS_2", "ADSM_CITY_ATTIKI_ANATOLIKI_3", "ADSM_CITY_EVIA_1", "ADSM_CITY_BOIOTIA_2", "ADSM_CITY_FTHIOTIDA_2", "ADSM_CITY_DRAMA_1", "ADSM_CITY_DRAMA_2", "ADSM_CITY_AXAIA_2", "ADSM_CITY_MESSINIA_1", "ADSM_CITY_IOANNINA_2", "ADSM_CITY_FOKIDA_2", "ADSM_CITY_PELLA_2", "ADSM_CITY_LARISA_2", "ADSM_CITY_LAKONIA_1", "ADSM_CITY_ATTIKI_DYTIKI_2", "ADSM_CITY_ATTIKI_ATHINA_14", "ADSM_CITY_SERRES_3", "ADSM_CITY_KOZANI_3", "ADSM_CITY_ARGOLIDA_2", "ADSM_CITY_EVIA_2", "ADSM_CITY_ARGOLIDA_3", "ADSM_CITY_AXAIA_3", "ADSM_CITY_LAKONIA_2", "ADSM_CITY_IOANNINA_4", "ADSM_CITY_MAGNISIA_4", "ADSM_CITY_IOANNINA_3", "ADSM_CITY_ZAKYNTHOS_1", "ADSM_CITY_ILIA_4", "ADSM_CITY_PREVEZA_1", "ADSM_CITY_ATTIKI_ATHINA_15", "ADSM_CITY_THESPROTIA_1", "ADSM_CITY_ILIA_5", "ADSM_CITY_ATTIKI_ATHINA_16", "ADSM_CITY_SERRES_4", "ADSM_CITY_IRAKLIO_4", "ADSM_CITY_KABALA_1", "ADSM_CITY_THESSALONIKI_5", "ADSM_CITY_AITOLOKARNANIA_5", "ADSM_CITY_KIKLADES_5", "ADSM_CITY_THESSALONIKI_4", "ADSM_CITY_THESSALONIKI_6", "ADSM_CITY_BOIOTIA_3", "ADSM_CITY_RODOPI_2", "ADSM_CITY_LASITHI_2", "ADSM_CITY_AITOLOKARNANIA_1", "ADSM_CITY_KIKLADES_6", "ADSM_CITY_KEFALLONIA_1", "ADSM_CITY_SAMOS_1", "ADSM_CITY_ATTIKI_ATHINA_17", "ADSM_CITY_EVIA_3", "ADSM_CITY_IOANNINA_5", "ADSM_CITY_DODEKANISA_5", "ADSM_CITY_DRAMA_3", "ADSM_CITY_KIKLADES_7", "ADSM_CITY_KERKIRA_1", "ADSM_CITY_KABALA_2", "ADSM_CITY_ATTIKI_ATHINA_18", "ADSM_CITY_AXAIA_4", "ADSM_CITY_MESSINIA_2", "ADSM_CITY_THESSALONIKI_7", "ADSM_CITY_TRIKALA_1", "ADSM_CITY_ATTIKI_ATHINA_19", "ADSM_CITY_DODEKANISA_3", "ADSM_CITY_XANIA_3", "ADSM_CITY_KARDITSA_2", "ADSM_CITY_DODEKANISA_4", "ADSM_CITY_EVRITANIA_2", "ADSM_CITY_EVIA_4", "ADSM_CITY_XALKIDIKI_2", "ADSM_CITY_KASTORIA_1", "ADSM_CITY_PIERIA_2", "ADSM_CITY_ARTA_3", "ADSM_CITY_ATTIKI_PIREAS_3", "ADSM_CITY_KEFALLONIA_2", "ADSM_CITY_ATTIKI_ATHINA_20", "ADSM_CITY_LARISA_3", "ADSM_CITY_KILKIS_1", "ADSM_CITY_KIKLADES_8", "ADSM_CITY_XANIA_4", "ADSM_CITY_KOZANI_4", "ADSM_CITY_RODOPI_3", "ADSM_CITY_THESSALONIKI_8", "ADSM_CITY_KORINTHIA_2", "ADSM_CITY_ATTIKI_PIREAS_4", "ADSM_CITY_ATTIKI_ANATOLIKI_4", "ADSM_CITY_ATTIKI_PIREAS_5", "ADSM_CITY_DODEKANISA_6", "ADSM_CITY_IOANNINA_6", "ADSM_CITY_KIKLADES_9", "ADSM_CITY_EVIA_5", "ADSM_CITY_DODEKANISA_8", "ADSM_CITY_LESVOS_2", "ADSM_CITY_LESVOS_3", "ADSM_CITY_KARDITSA_3", "ADSM_CITY_THESSALONIKI_9", "ADSM_CITY_FTHIOTIDA_3", "ADSM_CITY_LARISA_4", "ADSM_CITY_ATTIKI_ANATOLIKI_5", "ADSM_CITY_BOIOTIA_4", "ADSM_CITY_DODEKANISA_7", "ADSM_CITY_LEFKADA_1", "ADSM_CITY_FTHIOTIDA_4", "ADSM_CITY_KORINTHIA_3", "ADSM_CITY_ATTIKI_ATHINA_21", "ADSM_CITY_ATTIKI_DYTIKI_3", "ADSM_CITY_LAKONIA_3", "ADSM_CITY_KIKLADES_10", "ADSM_CITY_FTHIOTIDA_5", "ADSM_CITY_IRAKLIO_5", "ADSM_CITY_EVIA_6", "ADSM_CITY_ATTIKI_ANATOLIKI_6", "ADSM_CITY_ATTIKI_ANATOLIKI_7", "ADSM_CITY_RODOPI_4", "ADSM_CITY_DODEKANISA_9", "ADSM_CITY_ARKADIA_3", "ADSM_CITY_LEFKADA_2", "ADSM_CITY_ATTIKI_DYTIKI_4", "ADSM_CITY_MESSINIA_3", "ADSM_CITY_ATTIKI_ATHINA_22", "ADSM_CITY_IOANNINA_7", "ADSM_CITY_IRAKLIO_6", "ADSM_CITY_LAKONIA_4", "ADSM_CITY_ATTIKI_ATHINA_23", "ADSM_CITY_KARDITSA_4", "ADSM_CITY_KIKLADES_11", "ADSM_CITY_RETHIMNO_4", "ADSM_CITY_KSANTHI_3", "ADSM_CITY_FTHIOTIDA_6", "ADSM_CITY_KIKLADES_12", "ADSM_CITY_IMATHIA_3", "ADSM_CITY_SERRES_5", "ADSM_CITY_ATTIKI_ATHINA_24", "ADSM_CITY_XALKIDIKI_3", "ADSM_CITY_ATTIKI_ATHINA_25", "ADSM_CITY_KABALA_3", "ADSM_CITY_ATTIKI_PIREAS_6", "ADSM_CITY_AITOLOKARNANIA_6", "ADSM_CITY_ARGOLIDA_4", "ADSM_CITY_THESSALONIKI_10", "ADSM_CITY_KORINTHIA_4", "ADSM_CITY_KASTORIA_2", "ADSM_CITY_ARTA_4", "ADSM_CITY_DODEKANISA_10", "ADSM_CITY_ARKADIA_4", "ADSM_CITY_MAGNISIA_5", "ADSM_CITY_KSANTHI_1", "ADSM_CITY_AITOLOKARNANIA_7", "ADSM_CITY_KORINTHIA_5", "ADSM_CITY_XIOS_1", "ADSM_CITY_MESSINIA_4", "ADSM_CITY_KASTORIA_3", "ADSM_CITY_EVROS_3", "ADSM_CITY_LASITHI_3", "ADSM_CITY_BOIOTIA_5", "ADSM_CITY_PREVEZA_2", "ADSM_CITY_KIKLADES_13", "ADSM_CITY_DODEKANISA_11", "ADSM_CITY_PELLA_3", "ADSM_CITY_KABALA_4", "ADSM_CITY_ATTIKI_ANATOLIKI_8", "ADSM_CITY_KILKIS_2", "ADSM_CITY_ATTIKI_ATHINA_26", "ADSM_CITY_KARDITSA_5", "ADSM_CITY_ATTIKI_ANATOLIKI_9", "ADSM_CITY_KERKIRA_2", "ADSM_CITY_ATTIKI_ATHINA_27", "ADSM_CITY_DRAMA_4", "ADSM_CITY_AXAIA_5", "ADSM_CITY_THESSALONIKI_11", "ADSM_CITY_ATTIKI_PIREAS_7", "ADSM_CITY_ATTIKI_ATHINA_28", "ADSM_CITY_ATTIKI_PIREAS_8", "ADSM_CITY_ATTIKI_ATHINA_29", "ADSM_CITY_ATTIKI_ATHINA_30", "ADSM_CITY_ILIA_6", "ADSM_CITY_XANIA_5", "ADSM_CITY_XALKIDIKI_4", "ADSM_CITY_PREVEZA_3", "ADSM_CITY_FLORINA_2", "ADSM_CITY_DRAMA_5", "ADSM_CITY_THESSALONIKI_12", "ADSM_CITY_IOANNINA_8", "ADSM_CITY_ATTIKI_PIREAS_9", "ADSM_CITY_PIERIA_3", "ADSM_CITY_TRIKALA_2", "ADSM_CITY_MESSINIA_5", "ADSM_CITY_ILIA_7", "ADSM_CITY_MAGNISIA_6", "ADSM_CITY_ATTIKI_ANATOLIKI_10", "ADSM_CITY_RETHIMNO_5", "ADSM_CITY_DODEKANISA_12", "ADSM_CITY_SAMOS_2", "ADSM_CITY_KIKLADES_15", "ADSM_CITY_KIKLADES_16", "ADSM_CITY_ATTIKI_PIREAS_10", "ADSM_CITY_EVROS_4", "ADSM_CITY_ATTIKI_ANATOLIKI_11", "ADSM_CITY_KIKLADES_14", "ADSM_CITY_SERRES_6", "ADSM_CITY_LASITHI_4", "ADSM_CITY_XALKIDIKI_5", "ADSM_CITY_KORINTHIA_6", "ADSM_CITY_SERRES_7", "ADSM_CITY_MAGNISIA_7", "ADSM_CITY_MAGNISIA_8", "ADSM_CITY_PELLA_4", "ADSM_CITY_EVIA_7", "ADSM_CITY_THESPROTIA_2", "ADSM_CITY_EVROS_5", "ADSM_CITY_KARDITSA_6", "ADSM_CITY_LAKONIA_5", "ADSM_CITY_ATTIKI_ANATOLIKI_12", "ADSM_CITY_ATTIKI_PIREAS_11", "ADSM_CITY_FTHIOTIDA_7", "ADSM_CITY_XANIA_6", "ADSM_CITY_DODEKANISA_13", "ADSM_CITY_KIKLADES_17", "ADSM_CITY_DODEKANISA_14", "ADSM_CITY_KIKLADES_18", "ADSM_CITY_BOIOTIA_6", "ADSM_CITY_LARISA_5", "ADSM_CITY_KSANTHI_4", "ADSM_CITY_ARKADIA_5", "ADSM_CITY_TRIKALA_3", "ADSM_CITY_MESSINIA_6", "ADSM_CITY_ATTIKI_PIREAS_12", "ADSM_CITY_LARISA_6", "ADSM_CITY_ATTIKI_PIREAS_13", "ADSM_CITY_IRAKLIO_7", "ADSM_CITY_TRIKALA_4", "ADSM_CITY_LARISA_7", "ADSM_CITY_ATTIKI_ATHINA_31", "ADSM_CITY_THESPROTIA_3", "ADSM_CITY_ATTIKI_ATHINA_32", "ADSM_CITY_FLORINA_3", "ADSM_CITY_KIKLADES_19", "ADSM_CITY_SAMOS_3", "ADSM_CITY_ATTIKI_DYTIKI_5", "ADSM_CITY_XIOS_2", "ADSM_CITY_ATTIKI_ATHINA_34", "ADSM_CITY_THESSALONIKI_13", "ADSM_CITY_EVIA_8", "ADSM_CITY_XANIA_7", "ADSM_CITY_ATTIKI_ATHINA_33", "ADSM_CITY_IRAKLIO_8", "ADSM_CITY_XIOS_3", "ADSM_CITY_THESSALONIKI_14", "ADSM_CITY_ATTIKI_ANATOLIKI_13");


	$gr_cities_lang_sort = array();
	foreach ($dimoi as $dimos) {
		
		array_push($gr_cities_lang_sort , JText::_($dimos));
	}
	
	array_multisort($gr_cities_lang_sort, $dimoi);
	$i = 0;
	foreach ($dimoi as $dimos) {
		if ($i != 0) echo ',';
		echo  'new Array("'.JText::_($dimos).'","'.$dimos.'" )';
		$i++;
	}
}



function get_Nomous() {

	
	$nomoi = array(
		"ADSM_CITY_AITOLOKARNANIA",
		"ADSM_CITY_ARGOLIDA",
		"ADSM_CITY_ARKADIA",
		"ADSM_CITY_ARTA",
		"ADSM_CITY_ATTIKI_ATHINA",
		"ADSM_CITY_ATTIKI_ANATOLIKI",
		"ADSM_CITY_ATTIKI_DYTIKI",
		"ADSM_CITY_ATTIKI_PIREAS",
		"ADSM_CITY_AXAIA",
		"ADSM_CITY_BOIOTIA",
		"ADSM_CITY_GREVENA",
		"ADSM_CITY_DRAMA",
		"ADSM_CITY_DODEKANISA",
		"ADSM_CITY_EVROS",
		"ADSM_CITY_EVIA",
		"ADSM_CITY_EVRITANIA",
		"ADSM_CITY_ZAKYNTHOS",
		"ADSM_CITY_ILIA",
		"ADSM_CITY_IMATHIA",
		"ADSM_CITY_IRAKLIO",
		"ADSM_CITY_THESPROTIA",
		"ADSM_CITY_THESSALONIKI",
		"ADSM_CITY_IOANNINA",
		"ADSM_CITY_KABALA",
		"ADSM_CITY_KARDITSA",
		"ADSM_CITY_KASTORIA",
		"ADSM_CITY_KERKIRA",
		"ADSM_CITY_KEFALLONIA",
		"ADSM_CITY_KILKIS",
		"ADSM_CITY_KOZANI",
		"ADSM_CITY_KORINTHIA",
		"ADSM_CITY_KIKLADES",
		"ADSM_CITY_LAKONIA",
		"ADSM_CITY_LARISA",
		"ADSM_CITY_LASITHI",
		"ADSM_CITY_LESVOS",
		"ADSM_CITY_LEFKADA",
		"ADSM_CITY_MAGNISIA",
		"ADSM_CITY_MESSINIA",
		"ADSM_CITY_KSANTHI",
		"ADSM_CITY_PELLA",
		"ADSM_CITY_PIERIA",
		"ADSM_CITY_PREVEZA",
		"ADSM_CITY_RETHIMNO",
		"ADSM_CITY_RODOPI",
		"ADSM_CITY_SAMOS",
		"ADSM_CITY_SERRES",
		"ADSM_CITY_TRIKALA",
		"ADSM_CITY_FTHIOTIDA",
		"ADSM_CITY_FLORINA",
		"ADSM_CITY_FOKIDA",
		"ADSM_CITY_XALKIDIKI",
		"ADSM_CITY_XANIA",
		"ADSM_CITY_XIOS"
	);
	$i = 0;
	foreach ($nomoi as $nomos) {
		if ($i != 0) echo ',';
		echo get_Nomos_Dimous($nomos);
		$i++;
	}
}
function get_Nomos_Dimous($nomos) {
	$dimoi = '';
	for($i=1; $i < 50; $i++) {
		if (JText::_($nomos.'_'.$i) == $nomos.'_'.$i) break;
		if ($i != 1) $dimoi .= ',';
		$dimoi .= '"'.JText::_($nomos.'_'.$i).'"';
		$dimoi2 =  $nomos.'_'.$i;
		
	}
	$dimoi = 'new Array("'.JText::_($nomos).'", new Array('.$dimoi.'),"'.$nomos.'" )';
	return $dimoi;
}
?>
<script language="javascript" type="text/javascript">
var gr_cities=new Array(<?php get_Nomous();?>);
var perioxi = new Array(<?php get_dimous();?>);

var bl_cities=new Array(<?php get_bl_cities();?>);

var cy_cities=new Array(<?php get_Nomous_cy();?>);
var cy_perioxi = new Array(<?php get_dimous_cy();?>);


function load_Nomous_MAD(country, fnomos, fdimos, nomos, dimos, span_nomos, span_dimos, def_val_nomos, def_val_dimos) {
	if(country == 'gr'){var cities = gr_cities;}
	else if(country == 'cy'){var cities = cy_cities;}
	else{ var cities = bl_cities;}
	if (!def_val_nomos) def_val_nomos = "<?php echo JText::_('ADSMANAGER_SELECT');?>";
	var nomos_selected = false;
	var nomoi = fnomos;
	nomoi.options.length = 0; //clear
	nomoi.options[0]=new Option(def_val_nomos, "");
	for(j=0;j<cities.length;j++) {
		if(country != 'bl'){ nomoi.options[j+1]=new Option(cities[j][0], cities[j][2]);}
		else {		nomoi.options[j+1]=new Option(cities[j][0], cities[j][1]);}

		if (cities[j][0] == nomos) {
			nomoi.selectedIndex = j+1; 
			nomos_selected = true;
		}
	}
	if (nomos_selected) load_Dimous_MAD(fcountry,fnomos, fdimos, dimos, span_nomos, span_dimos, def_val_dimos);
}


function load_all_Dimous(fcountry,fnomos,span_dimos) {

	if(fcountry == 'gr'){var al_perioxi = perioxi;}
	if(fcountry == 'cy'){var al_perioxi = cy_perioxi;}
	
	var nomoi = fnomos;
	nomoi.options.length = 0; //clear
	nomoi.options[0]=new Option("<?php echo JText::_('ADSMANAGER_SELECT');?>", "");
	for(j=0;j<al_perioxi.length;j++) {
		nomoi.options[j+1]=new Option(al_perioxi[j][0], al_perioxi[j][1]);
		if (al_perioxi[j][0] == '') {
			nomoi.selectedIndex = j+1; 
			nomos_selected = true;
		}
	}
	set_span_title_MAD(span_dimos, span_dimos+'_span');

}


function load_Dimous_MAD(fcountry,fnomos, fdimos, dimos, span_nomos, span_dimos, def_val_dimos) {
	
	if(fcountry == 'gr'){var cities = gr_cities;}
	if(fcountry == 'cy'){var cities = cy_cities;}
	
	if (!def_val_dimos) def_val_dimos = "<?php echo JText::_('ADSMANAGER_SELECT');?>";
	var poli = fnomos;
	var selectedBoxValue=poli.value;
	var poliLength = 0;
	
	var perioxi = fdimos; 
	perioxi.options.length = 0; //clear
	perioxi.options[0]=new Option(def_val_dimos, "");
	
	set_span_title_MAD(span_nomos, span_nomos+'_span');
	set_span_title_MAD(span_dimos, span_dimos+'_span');
	
	
	var c;
	var cc;
	var i;
	var j;
	for(c=0;c<cities.length;c++) {
		if (cities[c][2] == selectedBoxValue) {
			poliLength=cities[c][1].length;
			cc=c;
		}
	}
	for(i=0;i<poli.options.length;i++) {
		if(selectedBoxValue==poli.options[i].value) {
			for(j=0;j<poliLength;j++) {
				perioxi.options[j+1]=new Option(cities[cc][1][j], cities[cc][2] + '_' + (parseInt(j)+1));
				if (cities[cc][1][j] == dimos) perioxi.selectedIndex = j+1; 
			}
		}
	}
}

function set_span_title_MAD(from, to) {
	if (document.getElementById(to) != null) {
		document.getElementById(to).innerHTML  = document.getElementById(from).options[document.getElementById(from).selectedIndex].text;
	}
}
</script>


